### ISSUE TITLE
the Currently Supported Unity Version link is broke

### ISSUE THREAD

**Issue by DracoWolfVR** [vrchat-community/creator-docs#103]
Page not Found
https://docs.vrchat.com/docs/migrating-to-a-newer-minor-unity-version
"Close all of your open projects.

Check the ### [Currently Supported Unity Version](https://docs.vrchat.com/docs/current-unity-version) and install the new version of Unity via Unity Hub."

**Comment by momo-the-monster** [comment]
Fixed, thanks!
