### ISSUE TITLE
Misleading description in avatar doc

### ISSUE THREAD

**Issue by Misaka-L** [vrchat-community/creator-docs#105]
https://github.com/vrchat-community/creator-docs/blob/2c9191c5fbb01063c99ea27fae6175b68448faab/Docs/docs/avatars/index.md?plain=1#L87

> -- as in, we don't have a way for you to input data from eye tracking devices--

It may be confuse since VRChat support native eye-tracking in some device (like Quest).

**Comment by miacrggcrh** [comment]
3rdtd
