### ISSUE TITLE
VRCInputMethod is no documented

### ISSUE THREAD

**Issue by mimyquality** [vrchat-community/creator-docs#142]
I am glad that [OnInputMethodChanged](https://creators.vrchat.com/worlds/udon/input-events/#oninputmethodchanged) has been implemented, making it easier to determine what kind of input device the player is using.  
On the other hand, since the contents of VRCInputMethod are not documented, it is unclear which specific hardware item corresponds to which item in this enum. For example, what is the difference between `Vive` and `ViveXr`?

**Comment by Faxmashine** [comment]
Thanks for making this request! I asked one of our engineers:

> Vive is a Vive controller running through SteamVR, while ViveXr is a Vive XR Elite Controller running via OpenXR. The former will stop existing as a controller type in the SteamVR Input 2.0 update, as all SteamVR Input 2.0 devices appear as one.

We'll add this info to our docs 👍

**Comment by Faxmashine** [comment]
https://creators.vrchat.com/worlds/udon/input-events/#oninputmethodchanged
![firefox_tKTYtBEMfw](https://github.com/vrchat-community/creator-docs/assets/117199600/b646ceae-0d27-4f89-99fb-f68c90f728d1)
