### ISSUE TITLE
Unity instructs not to use layer 31.

### ISSUE THREAD

**Issue by mimyquality** [vrchat-community/creator-docs#169]
Unity has long instructed us not to use layer 31.

> Warning: Layer 31 is used internally by the Editor’s Preview window mechanics. To prevent clashes, do not use this layer.

Source :  https://docs.unity3d.com/2022.3/Documentation/Manual/create-layers.html

31 layer is one of the user custom layers. You may wish to add this to the following page.
https://creators.vrchat.com/worlds/layers/

**Comment by Faxmashine** [comment]
I added this to our internal backlog!
