### ISSUE TITLE
Remove deprecated unity components included in Whitelisted Avatar Components

### ISSUE THREAD

**Issue by thatrobotdev** [vrchat-community/creator-docs#17]
Hello! I was reading through https://creators.vrchat.com/avatars/whitelisted-avatar-components/ and saw that the following links were broken:

* https://docs.unity3d.com/Manual/class-ParticleRenderer.html
* https://docs.unity3d.com/Manual/class-ParticleAnimator.html
* https://docs.unity3d.com/Manual/class-EllipsoidParticleEmitter.html
* https://docs.unity3d.com/Manual/class-MeshParticleEmitter.html
* https://docs.unity3d.com/Manual/class-GUILayer.html

According to an [official forum post](https://forum.unity.com/threads/legacy-particle-system-updater.510879/) and the blog post for [Unity 2018.3](https://blog.unity.com/technology/introducing-unity-2018-3), the legacy particle system used (including GameObjects using ParticleEmitter, ParticleAnimator, and ParticleRenderer) was completely removed. From what I can tell, these broken links are related to this change. Are there new particle components that should be added to this list/should these be removed? I can't find any related documention for these components at https://docs.unity3d.com/2019.4/Documentation/Manual/.

Additionally, with https://docs.unity3d.com/Manual/class-GUILayer.html, I think this component was completely removed in another deprecation (https://forum.unity.com/threads/removing-the-guilayer-guitext-guitexture-components.608770/).

**Comment by thatrobotdev** [comment]
I created #18 with my work on updating the documentation links, but these remain the outliers.

**Comment by Faxmashine** [comment]
You're correct! These classes are no longer part of the component whitelist and shouldn't be in the docs.

**Comment by momo-the-monster** [comment]
Is there anything else needed to close this issue as resolved?

**Comment by Faxmashine** [comment]
Ah, nope! We removed these components from the SDK and documentation a while back. 🎉🎉🎉

**Comment by thatrobotdev** [comment]
Thank you @Faxmashine and @momo-the-monster for tracking this! 🎉🎉🎉
