### ISSUE TITLE
Broken link in Updating Unity in updating SDK

### ISSUE THREAD

**Issue by Miamikicchi** [vrchat-community/creator-docs#99]
https://creators.vrchat.com/sdk/updating-the-sdk/#updating-unity

links to

https://creators.vrchat.com/sdk/upgrade/index

which is a broken link

**Comment by Docteh** [comment]
On that note somewhere in creator companion I got linked to https://creators.vrchat.com/sdk/current-unity-version which is currently 404

**Comment by FairplexVR** [comment]
> https://creators.vrchat.com/sdk/updating-the-sdk/#updating-unity
> 
> links to
> 
> https://creators.vrchat.com/sdk/upgrade/index
> 
> which is a broken link

Correct should be /sdk/upgrade

> On that note somewhere in creator companion I got linked to https://creators.vrchat.com/sdk/current-unity-version which is currently 404

Correct link:
https://creators.vrchat.com/sdk/upgrade/current-unity-version/

**Comment by Faxmashine** [comment]
This should all be fixed now! Thanks for the report.
